import 'react-phone-number-input/style.css'
import localFont from 'next/font/local'
import type { Metadata } from 'next'
import './globals.css'

const recoleta = localFont({
  variable: '--recoleta',
  src: [
    {
      path: '../../public/font/RecoletaAltRegular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
})

const helvetica = localFont({
  variable: '--helvetica',
  src: [
    {
      path: '../../public/font/HelveticaNeueLight.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${helvetica.variable} ${recoleta.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
